DearDiary/DearDiary.Web/Areas/Admin/Models/AddCategoryViewModel.cs
using DearDiary.Models;
using DearDiary.Web.AutoMapping;
using System.ComponentModel.DataAnnotations;

namespace DearDiary.Web.Areas.Admin.Models
{
    public class AddCategoryViewModel : IMapFrom<AimCategory>
    {
        [Required]
        [MinLength(3)]
        [MaxLength(30)]
        public string Name { get; set; }
    }
}

DearDiary/DearDiary.Web/Areas/Admin/Controllers/AddCategoryController.cs
using DearDiary.Models;
using DearDiary.Services.Contracts;
using DearDiary.Web.Areas.Admin.Models;
using DearDiary.Web.AutoMapping;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DearDiary.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AddCategoryController : Controller
    {
        private readonly IAimCategoryService categoryService;
        private readonly IMapperAdapter mapper;

        public AddCategoryController(IAimCategoryService categoryService, IMapperAdapter mapper)
        {
            if(categoryService == null)
            {
                throw new ArgumentNullException("Category Service cannot be null");
            }

            if (mapper == null)
            {
                throw new ArgumentNullException("Mapper cannot be null");
            }

            this.categoryService = categoryService;
            this.mapper = mapper;
        }

        // GET: Admin/AddCategory
        public ActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(AddCategoryViewModel categoryModel)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            }

            AimCategory newCategory = this.mapper.Map<AimCategory>(categoryModel);
            newCategory.Aims = new List<Aim>();

            try
            {
                this.categoryService.AddAimCategory(newCategory);
            }
            catch (Exception)
            {
                this.TempData.Add("Unique", "Duplicate element");
                return this.View();
            }

            this.TempData.Add("Category", "Successfully added the category");

            return this.Redirect($"/explore");            
        }
    }
}

DearDiary/DearDiary.Web/Areas/Admin/Views/AddCategory/Index.cshtml
@model DearDiary.Web.Areas.Admin.Models.AddCategoryViewModel

@{
    ViewBag.Title = "Add Category";
}

<h2>Add Category</h2>
@if (TempData["Unique"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Unique"]
    </div>
}
<div class="container main-content">
    @using (Html.BeginForm("Index", "AddCategory", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}