DearDiary/DearDiary.Web/Models/AimViewModel.cs
using DearDiary.Models;
using DearDiary.Web.AutoMapping;

namespace DearDiary.Web.Models
{
    public class AimViewModel : IMapFrom<Aim>
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public string OwnerUsername { get; set; }

        public string Photo { get; set; }
    }
}

DearDiary/DearDiary.Web/Models/AimsViewModel.cs
using DearDiary.Models;
using DearDiary.Web.AutoMapping;
using System.Collections.Generic;

namespace DearDiary.Web.Models
{
    public class AimsViewModel
    {
        public IEnumerable<AimViewModel> Aims { get; set; }
    }
}

DearDiary/DearDiary.Web/Models/CreateAimViewModel.cs
using DearDiary.Models;
using DearDiary.Web.AutoMapping;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;
using System.Web.Mvc;

namespace DearDiary.Web.Models
{
    public class CreateAimViewModel : IMapFrom<Aim>
    {
        [Required]        
        [Display(Name = "Name")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Description")]
        [StringLength(150, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 5)]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Status")]
        public string Status { get; set; }

        [Display(Name = "City")]
        public int CityId { get; set; }
        public IEnumerable<SelectListItem> Cities { get; set; }

        [Required]
        [Display(Name = "Country")]
        public int CountryId { get; set; }
        public IEnumerable<SelectListItem> Countries { get; set; }

        [Required]
        [Display(Name = "Photo")]
        [NotMapped]
        public HttpPostedFileBase Photo { get; set; }
        
        [Display(Name = "Owner username")]
        public string OwnerUsername { get; set; }

        [Required]
        [Display(Name = "Category")]
        public int AimCategoryId { get; set; }
        public IEnumerable<SelectListItem> AimCategories { get; set; }
    }
}

DearDiary/DearDiary.Web/Controllers/AimController.cs
using DearDiary.Models;
using DearDiary.Services.Contracts;
using DearDiary.Web.AutoMapping;
using DearDiary.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DearDiary.Web.Controllers
{
    public class AimController : Controller
    {
        private readonly IAimService aimService;
        private readonly ICityService cityService;
        private readonly IAimCategoryService aimCategoryService;
        private readonly ICountryService countryService;
        private readonly IMapperAdapter mapper;

        private const int CountOfAims = 5;

        public AimController(
            IAimService aimService,
            ICountryService countryService,
            ICityService cityService,
            IAimCategoryService aimCategoryService,
            IMapperAdapter mapper)
        {
            if(aimService == null)
            {
                throw new ArgumentNullException("Aim Service cannot be null");
            }

            if (countryService == null)
            {
                throw new ArgumentNullException("Country Service cannot be null");
            }

            if (cityService == null)
            {
                throw new ArgumentNullException("City Service cannot be null");
            }

            if (aimCategoryService == null)
            {
                throw new ArgumentNullException("Category Service cannot be null");
            }

            if (mapper == null)
            {
                throw new ArgumentNullException("Mapper cannot be null");
            }

            this.aimService = aimService;
            this.cityService = cityService;
            this.countryService = countryService;
            this.aimCategoryService = aimCategoryService;
            this.mapper = mapper;
        }

        public ActionResult Index()
        {
            return this.RedirectToRoute(new
            {
                controller = "Explore",
                action = "Index"
            });
        }

        // GET: Aim
        public ActionResult Details(string id)
        {
            if(id == null)
            {
                return RedirectToRoute(new
                {
                    controller = "Explore",
                    action = "Index"
                });
            }

            int aimId = int.Parse(id);
            Aim aim = this.aimService.GetAimById(aimId);

            if (aim == null)
            {
                return this.View("Error");
            }

            AimDetailsViewModel model = this.mapper.Map<AimDetailsViewModel>(aim);

            return this.View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = new CreateAimViewModel();

            ViewData["country"] = GetCountries();
            ViewData["category"] = GetCategories();
            //model.Countries = GetCountries();
            //model.AimCategories = GetCategories();

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateAimViewModel aimModel, FormCollection form)
        {
            if (!this.IsImage(aimModel.Photo))
            {
                ViewData["country"] = GetCountries();
                ViewData["category"] = GetCategories();
                return View();
            }

            int countryId = 0;
            int? cityId;
            try
            {
                countryId = int.Parse(form["Country"].ToString());
            }
            catch (Exception)
            {
                this.TempData.Add("Country", "Choose a valid country");
                return this.RedirectToAction("Create");
            }

            try
            {
                cityId = int.Parse(form["city"].ToString());
            }
            catch (Exception)
            {
                cityId = null;
                this.TempData.Add("City", "Choose a valid city");
                return this.RedirectToAction("Create");
            }

            int categoryId = 0;
            try
            {
                categoryId = int.Parse(form["category"].ToString());
            }
            catch (Exception)
            {
                this.TempData.Add("InvalidCategory", "Choose a valid category");
                return this.RedirectToAction("Create");
            }

            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                if (Request.Files.Count > 0)
                {
                    fileName = aimModel.Photo.FileName;
                    string path = this.Server.MapPath($"~/Images/{fileName}");

                    aimModel.Photo.SaveAs(path);
                }                

                Aim newAim = this.mapper.Map<Aim>(aimModel);

                newAim.CountryId = countryId;
                newAim.CityId = cityId;
                newAim.AimCategoryId = categoryId;
                newAim.OwnerUsername = this.User.Identity.Name;
                newAim.Photo = fileName;

                aimService.AddAim(newAim);
                this.TempData.Add("Addition", "Your aim was added successfully.");

                return RedirectToRoute(new
                {
                    controller = "Explore",
                    action = "Index"
                });
            }
            else
            {
                ViewData["country"] = GetCountries();
                ViewData["category"] = GetCategories();
                return View(aimModel);
            }            
        }

        public JsonResult GetCities(string id)
        {
            List<SelectListItem> cities = new List<SelectListItem>();

            var sortedCities = this.cityService.GetAllCitiesByCountry(id);

            foreach (var city in sortedCities)
            {
                cities.Add(new SelectListItem { Text = city.Name, Value = city.Id.ToString() });
            }

            return Json(new SelectList(cities, "Value", "Text"));
        }

        private bool IsImage(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return false;
            }

            var contentType = file.ContentType.ToLower();
            var result = contentType == "image/jpg"
                || contentType == "image/jpeg"
                || contentType == "image/png";

            return result;
        }

        private IEnumerable<SelectListItem> GetCities()
        {
            var c = this.cityService.GetAllCities().Select(x =>
               new SelectListItem
               {
                   Value = x.Id.ToString(),
                   Text = x.Name
               });

            return new SelectList(c, "Value", "Text");
        }

        private IEnumerable<SelectListItem> GetCountries()
        {
            var c = this.countryService.GetAllCountries().Select(x =>
               new SelectListItem
               {
                   Value = x.Id.ToString(),
                   Text = x.Name
               });

            return new SelectList(c, "Value", "Text");
        }

        private IEnumerable<SelectListItem> GetCategories()
        {
            var c = this.aimCategoryService.GetAimCategories().Select(x =>
               new SelectListItem
               {
                   Value = x.Id.ToString(),
                   Text = x.Name
               });

            return new SelectList(c, "Value", "Text");
        }
    }
}

DearDiary/DearDiary.Web/Views/Aim/Create.cshtml
@using DearDiary.Models

@model DearDiary.Web.Models.CreateAimViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Aim</h2>
<hr />
@if (TempData["Country"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Country"]
    </div>
}
@if (TempData["City"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["City"]
    </div>
}
@if (TempData["InvalidCategory"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["InvalidCategory"]
    </div>
}
    @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="loginBox">
            <div class="form-horizontal">
                <br />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>                

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, 5, 50, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Status", new SelectList(Enum.GetValues(typeof(Status))),
                                            "Please select status", new { style = "width:250px", @class = "dropdown1" })                        
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })                  
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CountryId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Country", ViewData["country"] as List<SelectListItem>, "Please select a country", new { style = "width:250px", @class = "dropdown1" })
                        @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })                    
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("city", new SelectList(string.Empty, "Value", "Text"), "", new { style = "width:250px", @class = "dropdown1" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AimCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Category", ViewData["category"] as List<SelectListItem>, "Please select a category", new { style = "width:250px", @class = "dropdown1" })
                        @Html.ValidationMessageFor(model => model.AimCategoryId, "", new { @class = "text-danger" })                    
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Photo, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Photo, new { type = "file" })
                        @Html.ValidationMessageFor(m => m.Photo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Back to List", "Index", "Aim", new { area = "" }, null)
                    </div>
                </div>
            </div>            
        </div>
    }    

@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
<script type="text/javascript">
     $(document).ready(function () {
         $("#Country").change(function () {
             $("#city").empty();
             $.ajax({
                 type: 'POST',
                 url: '@Url.Action("GetCities")', 
 
                 dataType: 'json',
 
                 data: { id: $("#Country").val() },
 
                 success: function (cities) {
                     
                     $.each(cities, function (i, city) {
                     $("#city").append('<option value="' + city.Value + '">' +
                          city.Text + '</option>');
                     });
                 },
                 error: function (ex) {
                     alert('Failed to retrieve cities.' + ex);
                 }
             });
             return false;
         })
     });
 </script>
}

DearDiary/DearDiary.Web/Views/Aim/CreateAim.cshtml
@using DearDiary.Models

@model DearDiary.Web.Models.CreateAimViewModel

@{
    ViewBag.Title = "CreateAim";
}

<h2>Create Aim</h2>
<hr />
    @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="loginBox">
            <div class="form-horizontal">
                <br />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>                

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, 5, 50, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Status", new SelectList(Enum.GetValues(typeof(Status))),
                                            "Select Status", new { @class = "form-control" })                        
                    </div>
                </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.CityId, Model.Cities)
                    </div>
                </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.CountryId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Country", ViewData["country"] as List<SelectListItem>)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("City", new SelectList(string.Empty, "Value", "Text"), "Please select a city", new { style = "width:250px", @class = "dropdown1" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AimCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Category", ViewData["category"] as List<SelectListItem>)
                    </div>
                </div>

                @*<div>
                    <label for="file">Upload Image:</label>
                    <input type="file" name="file" id="file" /><br><br>                    
                    @ViewBag.Message
                </div>*@
                <div class="form-group">
                    @Html.LabelFor(m => m.Photo, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Photo, new { type = "file" })
                        @Html.ValidationMessageFor(m => m.Photo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>            
        </div>
    }    

@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    

<script type="text/javascript">
    $(document).ready(function () {
        //Dropdownlist Selectedchange event
        $("#Country").change(function () {
            $("#City").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetCities")', // we are calling json method

                dataType: 'json',

                data: { id: $("#Country").val() },

                success: function (cities) {
                    // coties contains the JSON formatted list
                    // of cities passed from the controller

                    $.each(cities, function (i, city) {
                    $("#City").append('<option value="' + city.Value + '">' +
                         city.Text + '</option>');
                    // here we are adding option for States

                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve cities.' + ex);
                }
            });
            return false;
        })
    });
</script>
}

DearDiary/DearDiary.Web/Views/Aim/Details.cshtml
@model DearDiary.Web.Models.AimDetailsViewModel

@{
    ViewBag.Title = Model.Name;
}

<h2>@Model.Name details</h2>

<div class="row">
    <div class="col-md-3">
        <img class="img-responsive" src="@Url.Content($"~/Images/{Model.Photo}")" alt="@Model.Name" />
    </div>
    <div class="col-md-9">
        <h1>@Model.Name</h1>
        <h3>@Model.OwnerName</h3>
        <p>@Model.Description</p>
        <h5>@Model.CityName</h5>
        <h5>@Model.CountryName</h5>
       
        @if (this.User.Identity.IsAuthenticated)
            {
            <div class="btn-group">
                <button type="button" class="btn btn-primary">TO DO</button>
                <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">TO DO</a></li>
                    <li><a class="dropdown-item" href="#">Fulfilled</a></li>
                </ul>
            </div>
        }
    </div>
</div>

DearDiary/DearDiary.Web/Views/Aim/Index.cshtml
@model DearDiary.Web.Models.AimDetailsViewModel

@{
    ViewBag.Title = Model.Name;
}

<h2>@Model.Name details</h2>

<div class="row">
    <div class="col-md-3">
        <img class="img-responsive" src="@Url.Content($"~/Images/{Model.Photo}")" alt="@Model.Name" />
    </div>
    <div class="col-md-9">
        <h1>@Model.Name</h1>
        <h3>@Model.OwnerName</h3>
        <p>@Model.Description</p>
        <h5>@Model.CityName</h5>
        <h5>@Model.CountryName</h5>

       
        @if (this.User.Identity.IsAuthenticated)
            {
            <div class="btn-group">
                <button type="button" class="btn btn-primary">TO DO</button>
                <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">TO DO</a></li>
                    <li><a class="dropdown-item" href="#">Fulfilled</a></li>
                </ul>
            </div>
        }
    </div>
</div>